// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: notification_service/protobuf/email.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailSend struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Content       *EmailSend_EmailContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Recipients    []string                `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSend) Reset() {
	*x = EmailSend{}
	mi := &file_notification_service_protobuf_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSend) ProtoMessage() {}

func (x *EmailSend) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_protobuf_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSend.ProtoReflect.Descriptor instead.
func (*EmailSend) Descriptor() ([]byte, []int) {
	return file_notification_service_protobuf_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailSend) GetContent() *EmailSend_EmailContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *EmailSend) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type EmailSend_EmailContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSend_EmailContent) Reset() {
	*x = EmailSend_EmailContent{}
	mi := &file_notification_service_protobuf_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSend_EmailContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSend_EmailContent) ProtoMessage() {}

func (x *EmailSend_EmailContent) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_protobuf_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSend_EmailContent.ProtoReflect.Descriptor instead.
func (*EmailSend_EmailContent) Descriptor() ([]byte, []int) {
	return file_notification_service_protobuf_email_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EmailSend_EmailContent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailSend_EmailContent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_notification_service_protobuf_email_proto protoreflect.FileDescriptor

var file_notification_service_protobuf_email_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0xa2, 0x01, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x6e, 0x64,
	0x12, 0x37, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53,
	0x65, 0x6e, 0x64, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x3c, 0x0a, 0x0c, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x1f, 0x5a, 0x1d, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_notification_service_protobuf_email_proto_rawDescOnce sync.Once
	file_notification_service_protobuf_email_proto_rawDescData []byte
)

func file_notification_service_protobuf_email_proto_rawDescGZIP() []byte {
	file_notification_service_protobuf_email_proto_rawDescOnce.Do(func() {
		file_notification_service_protobuf_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_protobuf_email_proto_rawDesc), len(file_notification_service_protobuf_email_proto_rawDesc)))
	})
	return file_notification_service_protobuf_email_proto_rawDescData
}

var file_notification_service_protobuf_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_service_protobuf_email_proto_goTypes = []any{
	(*EmailSend)(nil),              // 0: email.EmailSend
	(*EmailSend_EmailContent)(nil), // 1: email.EmailSend.EmailContent
}
var file_notification_service_protobuf_email_proto_depIdxs = []int32{
	1, // 0: email.EmailSend.content:type_name -> email.EmailSend.EmailContent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_service_protobuf_email_proto_init() }
func file_notification_service_protobuf_email_proto_init() {
	if File_notification_service_protobuf_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_protobuf_email_proto_rawDesc), len(file_notification_service_protobuf_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_service_protobuf_email_proto_goTypes,
		DependencyIndexes: file_notification_service_protobuf_email_proto_depIdxs,
		MessageInfos:      file_notification_service_protobuf_email_proto_msgTypes,
	}.Build()
	File_notification_service_protobuf_email_proto = out.File
	file_notification_service_protobuf_email_proto_goTypes = nil
	file_notification_service_protobuf_email_proto_depIdxs = nil
}
