// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: notification_service/protobuf/tg.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramMessageSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Recipients    []string               `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramMessageSend) Reset() {
	*x = TelegramMessageSend{}
	mi := &file_notification_service_protobuf_tg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramMessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramMessageSend) ProtoMessage() {}

func (x *TelegramMessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_protobuf_tg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramMessageSend.ProtoReflect.Descriptor instead.
func (*TelegramMessageSend) Descriptor() ([]byte, []int) {
	return file_notification_service_protobuf_tg_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramMessageSend) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TelegramMessageSend) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

var File_notification_service_protobuf_tg_proto protoreflect.FileDescriptor

var file_notification_service_protobuf_tg_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x4f, 0x0a, 0x13, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x42, 0x1f, 0x5a, 0x1d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_notification_service_protobuf_tg_proto_rawDescOnce sync.Once
	file_notification_service_protobuf_tg_proto_rawDescData []byte
)

func file_notification_service_protobuf_tg_proto_rawDescGZIP() []byte {
	file_notification_service_protobuf_tg_proto_rawDescOnce.Do(func() {
		file_notification_service_protobuf_tg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_protobuf_tg_proto_rawDesc), len(file_notification_service_protobuf_tg_proto_rawDesc)))
	})
	return file_notification_service_protobuf_tg_proto_rawDescData
}

var file_notification_service_protobuf_tg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notification_service_protobuf_tg_proto_goTypes = []any{
	(*TelegramMessageSend)(nil), // 0: email.TelegramMessageSend
}
var file_notification_service_protobuf_tg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_service_protobuf_tg_proto_init() }
func file_notification_service_protobuf_tg_proto_init() {
	if File_notification_service_protobuf_tg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_protobuf_tg_proto_rawDesc), len(file_notification_service_protobuf_tg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_service_protobuf_tg_proto_goTypes,
		DependencyIndexes: file_notification_service_protobuf_tg_proto_depIdxs,
		MessageInfos:      file_notification_service_protobuf_tg_proto_msgTypes,
	}.Build()
	File_notification_service_protobuf_tg_proto = out.File
	file_notification_service_protobuf_tg_proto_goTypes = nil
	file_notification_service_protobuf_tg_proto_depIdxs = nil
}
